[package]
name = "spru"
version = "0.1.0"
edition = "2024"

[features]
default = []
# For internal test usage only
test-util = []

[dev-dependencies]

[dependencies]
spru-macro = { path = "../spru-macro" }

telety.workspace = true
amass.workspace = true
tagset.workspace = true

halfbrown.workspace = true
thiserror.workspace = true

# temporary until proper errors are done
anyhow.workspace = true

derive_more = { workspace = true, features = ["from"] }
derive-where.workspace = true

deku.workspace = true

# serialization
serde.workspace = true
rmp-serde.workspace = true
erased-serde.workspace = true
