[package]
name = "spru"
version = "0.1.0"
edition = "2024"
description = "Reusable components for the spru strategy and digital board game framework."
license.workspace = true
repository.workspace = true
categories = ["game-development", "wasm"]
keywords = ["gamedev", "framework", "game", "wasm"]

[features]
default = []
# For internal test usage only
test-util = []

[dev-dependencies]

[dependencies]
spru-macro.workspace = true

telety.workspace = true
tagset.workspace = true

halfbrown.workspace = true
thiserror.workspace = true

derive_more = { workspace = true, features = ["from"] }
derive-where.workspace = true

implied-bounds.workspace = true

deku.workspace = true

tracing-core.workspace = true
tracing.workspace = true

uuid.workspace = true

# serialization
serde.workspace = true
rmp-serde.workspace = true
serde_bytes.workspace = true