[package]
name = "spru-bevy"
version = "0.1.0"
edition = "2024"

[features]
default = ["server", "client"]
server = []
client = []

[dependencies]
spru = { path = "../spru/" }

bevy.workspace = true

serde.workspace = true

thiserror.workspace = true

uuid.workspace = true

derive-where.workspace = true

[dev-dependencies]
spru-test = { path = "../spru-test/" }