[package]
name = "spru-bevy"
version = "0.1.0"
edition = "2024"
description = "bevy plugins for the spru strategy and digital board game framework."
license.workspace = true
repository.workspace = true
categories = ["game-development", "wasm"]
keywords = ["gamedev", "framework", "game", "wasm", "bevy"]

[features]
default = ["server", "client"]
server = []
client = []

[dependencies]
spru = { path = "../spru/" }

bevy.workspace = true

serde.workspace = true

thiserror.workspace = true

uuid.workspace = true

derive-where.workspace = true

# Only needed to qualify TagSet::Repr, hopefully can be removed in the future
tagset.workspace = true

[dev-dependencies]
spru-test = { path = "../spru-test/" }