[package]
name = "spru-bevy"
version = "0.1.0"
edition = "2024"
description = "bevy plugins for the spru strategy and digital board game framework."
license.workspace = true
repository.workspace = true
categories = ["game-development", "wasm"]
keywords = ["gamedev", "framework", "game", "wasm", "bevy"]

[features]
default = ["server", "client", "remote", "script"]
server = ["aeronet_webtransport?/server"]
client = ["aeronet_webtransport?/client"]
remote = ["dep:aeronet", "aeronet_webtransport/server", "dep:url"]
script = ["dep:spru-script"]

[dependencies]
spru.workspace = true
spru-script = { workspace = true, optional = true }

bevy.workspace = true

serde.workspace = true
rmp-serde.workspace = true

scopeguard.workspace = true

thiserror.workspace = true

uuid.workspace = true

derive-where.workspace = true

# Only needed to qualify TagSet::Repr, hopefully can be removed in the future
tagset.workspace = true

aeronet = { workspace = true, optional = true }
aeronet_webtransport = { workspace = true, optional = true }
url = { workspace = true, optional = true }

[dev-dependencies]
spru-test = { path = "../spru-test/" }