[package]
name = "spru-quibbler"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spru = { path = "../spru/" }
spru-util = { path = "../spru-util" }
spru-bevy = { path = "../spru-bevy" }

amass.workspace = true
tagset.workspace = true
telety.workspace = true

rand.workspace = true
rand_chacha.workspace = true

rust-fsm.workspace = true

thiserror.workspace = true
anyhow.workspace = true

serde.workspace = true
ron.workspace = true

tracing.workspace = true

# Ideally this would be a bevy-console, but its not updated for bevy 0.17 yet
bevy_simple_text_input = "0.12.0"
wordnik_list = "0.2.1"
bevy-inspector-egui = "=0.34.0"

#bevy_ratatui = "0.9.3"

arboard = "3.6.1"

[dependencies.bevy]
workspace = true
features = ["default"]

