[package]
name = "spru-quibbler"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spru.workspace = true
spru-util.workspace = true
spru-bevy.workspace = true
spru-script.workspace = true
spru-script-rhai.workspace = true

tagset.workspace = true
telety.workspace = true

rand.workspace = true
rand_chacha.workspace = true

rust-fsm.workspace = true

thiserror.workspace = true
anyhow.workspace = true

serde.workspace = true
ron.workspace = true

rhai = { workspace = true, features = ["serde"] }

tracing.workspace = true

itertools.workspace = true

wordnik_list = "0.2.1"
bevy-inspector-egui = { version = "0.37.0", optional = true }
bevy_egui = { version = "0.40.1", optional = true }

aeronet = { workspace = true, optional = true }
aeronet_webtransport = { workspace = true, optional = true }

[target.'cfg(not(all(target_family = "wasm", target_os = "unknown")))'.dependencies]
# no clipboard on wasm
arboard = "3.6.1"

[dependencies.bevy]
workspace = true
features = ["default"]

[build-dependencies]
copy_to_output.workspace = true

[features]
# non-WASM compatible
default = ["hybrid"]

# "role" features
dedicated-client = ["client", "remote", "ui"]
local = ["server", "client", "ui"]
# non-WASM compatible
dedicated-server = ["server", "remote"]
hybrid = ["local", "dedicated-server", "dedicated-client"]

# sub-features
client = ["spru-bevy/client"]
server = ["spru-bevy/server"]
remote = ["spru-bevy/remote", "dep:aeronet", "dep:aeronet_webtransport"]
# TODO bevy/bevy_egui should be trimmed for dedicated servers
ui = ["dep:bevy_egui", "dep:bevy-inspector-egui"]