[package]
name = "spru-script-lua"
version = "0.1.0"
edition = "2024"
description = "A lua scripting implementation for the spru framework."
license.workspace = true
repository.workspace = true
categories = ["game-development", "wasm"]
keywords = ["gamedev", "framework", "game", "scripting", "lua"]

[dev-dependencies]
spru = { workspace = true, features = ["test-util"] }
spru-util.workspace = true

[dependencies]
spru.workspace = true
spru-macro.workspace = true
spru-script.workspace = true

tagset.workspace = true
telety.workspace = true

derive-where.workspace = true

mlua = { version = "0.11.6", features = ["lua55", "vendored", "error-send", "send"] }

append-only-vec.workspace = true

serde.workspace = true

tracing.workspace = true

[features]
default = []