[workspace]
resolver = "2"
members = [
    "spru",
	"spru-bevy",
	"spru-macro", 
	"spru-quibbler", 
    "spru-script",
    "spru-script-base", 
    "spru-script-base-macro",
    "spru-script-rhai",
    "spru-script-rhai-macro",
    "spru-script-macro",
	"spru-test",
	"spru-util", 
]

[workspace.package]
license = "MIT OR Apache-2.0"
repository = "https://github.com/colinjneville/spru"

[workspace.dependencies]
spru-macro = { version = "0.1", path = "./spru-macro" }
spru = { version = "0.1", path = "./spru" }
spru-util = { version = "0.1", path = "./spru-util" }
spru-bevy = { version = "0.1", path = "./spru-bevy" }
spru-script-macro = { version = "0.1", path = "./spru-script-macro" }
spru-script = { version = "0.1", path = "./spru-script" }
spru-script-base = { version = "0.1", path = "./spru-script-base" }
spru-script-base-macro = { version = "0.1", path = "./spru-script-base-macro" }
spru-script-rhai = { version = "0.1", path = "./spru-script-rhai" }
spru-script-rhai-macro = { version = "0.1", path = "./spru-script-rhai-macro" }

telety = "0.4"
tagset = "0.1.3"

halfbrown = { version = "0.3.0", features = ["serde"] }
thiserror = "2.0.12"
anyhow = "1.0.100"
append-only-vec = "0.1.8"
itertools = "0.15.0"
scopeguard = "1.2.0"

bytemuck = { version = "1.25.0", features = ["extern_crate_alloc"] }

derive_more = "1.0.0"
derive-where = { version = "1.6.0", features = ["serde"] }
num-traits = "0.2.17"

implied-bounds = "0.1.0"

rand = { version = "0.9.1", features = [  ] }
rand_chacha = "0.9.0"

rust-fsm = "0.8.0"

uuid = { version = "1.18.1", features = [ "v4", "serde" ] }

# scripting
rhai = "1.24.0"

# logging
tracing = "0.1.41"
tracing-core = "0.1.34"

# networking
aeronet = "0.20.0"
aeronet_webtransport = "0.20.0"
url = "2.5.8"

# async
# atomicell = "0.2.0"
# futures-io = "0.3.31"
# moro = "0.4.0"

# async (smol ecosystem)
# async-broadcast = "0.7.2"
# async-lazy = "0.1.0"
# async-once-cell = "0.5.3"
# async-task = "4.7.1"
# async-trait = "0.1.81"
# event-listener = "5.3.1"
# futures-lite = "2.3.0"
# onetime = "0.1.2"
# smol = "2.0.0"

# macros
proc-macro2 = { version = "1.0.106", features = ["span-locations"] }
quote = "1.0.33"
syn = { version = "2.0.38", features = ["full"] }

vacro-parser = "0.1.15"
vacro-report = "0.1.3"

# serialization
rmp-serde = "=1.3.0"
deku = "0.18.1"
ron = "0.11.0"
serde_bytes = "0.11.19"

# build.rs
# A pull request with fixes for workspaces
copy_to_output = { git = "https://github.com/samwoodhams/copy_to_output", rev = "270cffc" }

[workspace.dependencies.serde]
version = "1.0.189"
features = [
    "std",
    "derive",
    "rc",
]

[workspace.dependencies.bevy]
version = "0.18.1"
default-features = false
features = [
    "bevy_log",
]
