[workspace]
resolver = "2"
members = [
    "spru",
	"spru-bevy",
	"spru-macro", 
	"spru-quibbler", 
	"spru-test",
	"spru-util",
]

[workspace.dependencies]
telety = "0.3"
amass = "0.1.1"
tagset = "0.1.1"

halfbrown = { version = "0.3.0", features = ["serde"] }
thiserror = "2.0.12"
anyhow = "1.0.100"

derive_more = "1.0.0"
derive-where = { version = "1.5.0", features = ["serde"] }
num-traits = "0.2.17"

implied-bounds = "0.1.0"

rand = { version = "0.9.1", features = [  ] }
rand_chacha = "0.9.0"

rust-fsm = "0.8.0"



spaghetto = { version = "0.0.3", features = ["serde"] }

uuid = { version = "1.18.1", features = [ "v4", "serde" ] }

# logging
tracing = "0.1.41"
tracing-core = "0.1.34"

# async
atomicell = "0.2.0"
futures-io = "0.3.31"
moro = "0.4.0"

# async (smol ecosystem)
# async-broadcast = "0.7.2"
# async-lazy = "0.1.0"
# async-once-cell = "0.5.3"
# async-task = "4.7.1"
# async-trait = "0.1.81"
# event-listener = "5.3.1"
# futures-lite = "2.3.0"
# onetime = "0.1.2"
# smol = "2.0.0"

# macros
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = "2.0.38"

# serialization
rmp-serde = "=1.3.0"
erased-serde = "0.4.5"
deku = "0.18.1"
ron = "0.11.0"
serde_bytes = "0.11.19"

[workspace.dependencies.serde]
version = "1.0.189"
features = [
    "std",
    "derive",
    "rc",
]

[workspace.dependencies.bevy]
version = "0.17.2"
default-features = false
features = [
    "bevy_log",
]

[patch.crates-io]
telety = { path = "D:/Projects/telety-ws/telety" } 
telety-macro = { path = "D:/Projects/telety-ws/telety-macro" } 
telety-impl = { path = "D:/Projects/telety-ws/telety-impl" } 
amass = { path = "D:/Projects/amass/amass" } 
#tagset = { git = "https://github.com/colinjneville/tagset.git" }
tagset = { path = "D:/Projects/tagit/tagset" }
#tagset-macro = { git = "https://github.com/colinjneville/tagset.git" }
tagset-macro = { path = "D:/Projects/tagit/tagset-macro" }