[package]
name = "spru-test"
version = "0.1.0"
edition = "2024"

[features]
default = []
bevy = []

[dependencies]
spru = { path = "../spru" }
spru-util = { path = "../spru-util" }

telety.workspace = true
amass.workspace = true
tagset.workspace = true

anyhow.workspace = true
thiserror.workspace = true
rand.workspace = true

derive_more = { workspace = true, features = ["from"] }
derive-where.workspace = true

serde.workspace = true

[dev-dependencies]
tracing.workspace = true
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }