[package]
name = "spru-util"
version = "0.1.0"
edition = "2024"
description = "An experimental framework for building multiplayer strategy and digital board games."
license.workspace = true
repository.workspace = true
categories = ["game-development", "wasm"]
keywords = ["gamedev", "framework", "game", "wasm"]

[dev-dependencies]
spru = { path = "../spru", features = ["test-util"] }

[dependencies]
spru = { path = "../spru" }
spru-macro = { path = "../spru-macro" }

tagset.workspace = true
telety.workspace = true

derive-where.workspace = true
num-traits.workspace = true
rand.workspace = true
rand_chacha.workspace = true
thiserror.workspace = true

tracing.workspace = true

rust-fsm = { workspace = true, optional = true }
serde.workspace = true

[features]
default = ["fsm"]
fsm = ["dep:rust-fsm"]