[package]
name = "spru-script-impl-types"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
description = "Parsers for spru-script macro implementations."
license.workspace = true
repository.workspace = true

[lib]

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

vacro-parser.workspace = true
vacro-report.workspace = true