[package]
name = "spru-script"
version = "0.1.0"
edition = "2024"
description = "Scripting support for the spru framework."
license.workspace = true
repository.workspace = true
categories = ["game-development", "wasm"]
keywords = ["gamedev", "framework", "game", "wasm", "scripting"]

[dev-dependencies]
spru = { workspace = true, features = ["test-util"] }

[dependencies]
spru.workspace = true
spru-script-macro.workspace = true

tagset.workspace = true
telety.workspace = true

derive-where.workspace = true

tracing.workspace = true

[features]
default = []
