[package]
name = "spru-script-rhai"
version = "0.1.0"
edition = "2024"
description = "A rhai scripting implementation for the spru framework."
license.workspace = true
repository.workspace = true
categories = ["game-development", "wasm"]
keywords = ["gamedev", "framework", "game", "scripting", "rhai"]

[dev-dependencies]
spru = { workspace = true, features = ["test-util"] }
spru-util.workspace = true
spru-script.workspace = true

[dependencies]
spru.workspace = true
spru-macro.workspace = true
spru-script.workspace = true
spru-script-base.workspace = true
spru-script-macro.workspace = true
spru-script-rhai-macro.workspace = true

tagset.workspace = true
telety.workspace = true

append-only-vec.workspace = true

derive-where.workspace = true

rhai = { workspace = true, features = ["serde", "sync"] }

serde.workspace = true

tracing.workspace = true

[features]
default = []