name: Build WASM demo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm32-unknown-unknown target
      run: rustup target add wasm32-unknown-unknown
    - name: Install cargo binstall
      run: >
        curl -L --proto '=https' --tlsv1.2 
        -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - name: Download wasm-bindgen
      run: cargo binstall wasm-bindgen-cli --no-confirm
    - name: Build wasm32-unknown-unknown
      run: cargo build --verbose --release -p spru-quibbler --target wasm32-unknown-unknown
    - name: Run wasm-bindgen
      run: wasm-bindgen --out-name wasm-quibbler --out-dir ./spru-quibbler/wasm --target web ./target/wasm32-unknown-unknown/release/spru-quibbler.wasm
    - name: Upload WASM artifacts 
      uses: actions/upload-pages-artifact@v4
      with:
        name: wasm-quibbler
        path: ./spru-quibbler/wasm

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
